### ISSUE TITLE
  plugin 2.5.2.  credit card, If the payment selection comes with the credit card fields, NO INPUT  possible!

### ISSUE THREAD

**Issue by oremountains** [mollie/Shopware#412] opened 2024-04-28 18:28 UTC
There is another problem with plugin 2.5.2. With credit card,

If the payment selection comes with the credit card fields, NO INPUT  possible!

The order can continue to be processed because the Mollie window then appears to enter the credit card details, 
but this irritates the customers.

I installed 2.4 again

**Comment by jensorben** [comment] 2024-05-03 08:53
We have the same problem since Version 2.5.0. Neither 2.5.1 nor 2.5.2 will fix it!

So we stay on 2.4.0, too and are not able to activate TWINT payment method for swiss customers!!!

**Comment by ThLind** [comment] 2024-05-06 12:11
I tried to reproduce the problem, but it seems to work at my local installation with version2.5.2:
![image](https://github.com/mollie/Shopware/assets/40621547/2ee65edf-3a51-4ea1-8225-e115a872cfa6)

**Comment by oremountains** [comment] 2024-05-06 13:34
i have Version SW  5.2.5 
The problem only occurs if you change the payment method in the account and then no data can be entered there.
The cursor flashes on the input field but cannot be entered and there is no error message

When you check out, you'll see the Mollie page with the credit card fields anyway.

I have now solved the problem differently - you just have to deactivate the components and styling for the credit card in the plugin

**Comment by BlackScorp** [comment] 2024-05-27 07:48
@jensorben @oremountains sorry for the late response.

i still cannot reproduce the error. what i tried

1) select credit card as default payment method for the customer
2) go to checkout, edit the payment methods in checkout and typed in the credit card data
3) complete checkout
4) go into admin and check that the new order exists
5) edit order details to check if mollie id is set


everything worked without problems. tried in Chrome.

can you write down the steps what youre doing so i can reproduce the problem?

**Comment by BlackScorp** [comment] 2024-05-27 09:10
@jensorben @oremountains can you try the build from here https://github.com/mollie/Shopware/actions/runs/9252154470/artifacts/1540304894

i changed something in the controller, since i dont have the plugin Virtual Variants i cannot test it properly

**Comment by BlackScorp** [comment] 2024-06-18 09:56
will be #fixed in next release

**Closed by BlackScorp** 2024-06-18 09:56 UTC
