### ISSUE TITLE
2.5.2 Error Cannot send headers; headers already sent in ,../httpdocs/custom/plugins/MollieShopware/Controllers/Frontend/Mollie.php, line 526 in ,../httpdocs/engine/Library/Enlight/Controller/Response/ResponseHttp.php:37

### ISSUE THREAD

**Issue by oremountains** [mollie/Shopware#410] opened 2024-04-22 05:02 UTC
i have new eroor messages 
Cannot send headers; headers already sent in ,../httpdocs/custom/plugins/MollieShopware/Controllers/Frontend/Mollie.php, line 526 
in ,../httpdocs/engine/Library/Enlight/Controller/Response/ResponseHttp.php:37

    "uri": "/Mollie/components?ext=.js&ts=1713761134",
    "method": "GET",
    "query": {
        "ext": ".js",
        "ts": "1713761134",
        "module": "frontend",
        "controller": "Mollie",
        "action": "components"
    },
    "post": []
}

**Comment by jensorben** [comment] 2024-05-03 09:08
We got the same error on the components.js:

// get controller
var mollieController = document.querySelector('div.mollie-components-controller');

// remove existing mollie controller
if (mollieController !== undefined && mollieController !== null) {
    mollieController.remove();
}

// get container
var cardToken = document.querySelector('#cardToken');

if (cardToken !== undefined) {
    // Initialize Mollie Components instance
    // eslint-disable-next-line no-undef
    const mollie = Mollie('pfl_3pAgcm3KRd', {
        locale: 'de_DE',
        // eslint-disable-next-line no-undef
        testmode: false,
    });

    // Default properties
    const properties = {
        styles: {
            base: {
                backgroundColor: '#fff',
                fontSize: '14px',
                padding: '10px 10px',
                '::placeholder': {
                    color: 'rgba(68, 68, 68, 0.2)',
                },
            },
            valid: {
                color: '#090',
            },
            invalid: {
                backgroundColor: '#fff1f3',
            },
        },
    };

    const cardHolder = {
        name: 'cardHolder',
        id: '#cardHolder',
        errors: 'cardHolderError',
    };
    const cardNumber = {
        name: 'cardNumber',
        id: '#cardNumber',
        errors: 'cardNumberError',
    };
    const expiryDate = {
        name: 'expiryDate',
        id: '#expiryDate',
        errors: 'expiryDateError',
    };
    const verificationCode = {
        name: 'verificationCode',
        id: '#verificationCode',
        errors: 'verificationCodeError',
    };

    const inputs = [cardHolder, cardNumber, expiryDate, verificationCode];

    // Event helpers
    const setFocus = (componentName, isFocused) => {
        const element = document.querySelector(componentName);
        element.classList.toggle('is-focused', isFocused);
    };

    const disableForm = () => {
        const submitButtons = document.querySelectorAll('button[type="submit"]');
        if (submitButtons.length > 0) {
            submitButtons.forEach(function(el) {
                el.disabled = true;
            });
        }
    };

    const enableForm = () => {
        const submitButtons = document.querySelectorAll('button[type="submit"]');
        if (submitButtons.length > 0) {
            submitButtons.forEach(function(el) {
                el.disabled = false;
            });
        }
    };

    // Elements
    const form = document.getElementById('shippingPaymentForm');

    // Create inputs
    inputs.forEach((element, index, arr) => {
        const component = mollie.createComponent(element.name, properties);
        component.mount(element.id);
        arr[index][element.name] = component;

        // Handle errors
        component.addEventListener('change', event => {
            const componentContainer = document.getElementById(`${element.name}`);
            const componentError = document.getElementById(`${element.errors}`);

            if (event.error && event.touched) {
                componentContainer.classList.add('error');
                componentError.textContent = event.error;
            } else {
                componentContainer.classList.remove('error');
                componentError.textContent = '';
            }
        });

        // Handle labels
        component.addEventListener('focus', () => {
            setFocus(`${element.id}`, true);
        });
        component.addEventListener('blur', () => {
            setFocus(`${element.id}`, false);
        });
    });

    // Submit handler
    form.addEventListener('submit', async event => {
        event.preventDefault();
        disableForm();

        // Reset possible form errors
        const verificationErrors = document.getElementById(`${verificationCode.errors}`);
        verificationErrors.textContent = '';

        // Get a payment token
        const { token, error } = await mollie.createToken();

        if (error) {
            enableForm();
            verificationErrors.textContent = error.message;
            return;
        }

        // Add token to the form
        const tokenInput = document.getElementById('cardToken');
        tokenInput.setAttribute('value', token);

        // Re-submit form to the server
        form.submit();
    });
}
<br /> 
<b>Fatal error</b>:  Uncaught RuntimeException: Cannot send headers; headers already sent in /var/www/clients/client1/web2/web/_exdev/custom/plugins/MollieShopware/Controllers/Frontend/Mollie.php, line 526 in /var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Controller/Response/ResponseHttp.php:307
Stack trace:
#0 /var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Controller/Response/ResponseHttp.php(145): Enlight_Controller_Response_ResponseHttp-&gt;canSendHeaders()
#1 /var/www/clients/client1/web2/web/_exdev/custom/plugins/intoVirtualVariants/intoVirtualVariants.php(40): Enlight_Controller_Response_ResponseHttp-&gt;setHeader()
#2 /var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Event/Handler/Default.php(90): intoVirtualVariants\intoVirtualVariants-&gt;onPostDispatch()
#3 /var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Event/EventManager.php(208): Enlight_Event_Handler_Default-&gt;execute()
#4 /var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Controller/Action.php(219): in <b>/var/www/clients/client1/web2/web/_exdev/engine/Library/Enlight/Controller/Response/ResponseHttp.php</b> on line <b>307</b><br />

**Comment by BlackScorp** [comment] 2024-05-27 07:53
@oremountains @jensorben can you explain where do you see those errors? 

@jensorben i see in your stacktrace that the introVirtualVariants plugin sends an error. can you try to disable the plugin an check it? maybe there is a compatibility problem with our plugin

**Comment by BlackScorp** [comment] 2024-05-27 12:45
@jensorben @oremountains i made some changes, can you try this version out?

https://github.com/mollie/Shopware/actions/runs/9252154470/artifacts/1540304894

its hard to reproduce for me since i dont have the introVirtualVarians extensions

**Comment by jensorben** [comment] 2024-05-28 13:03
@BlackScorp We downloaded your latest version and just replaced the files in the folder! Without disabling the intoVirtualVariants plugin your version worked fine and as normally expected!
Good job! We'll do some further testings next week but we think you solved the problem. Will your changes went into a new version of the plugin (expecting V 2.5.3 for an official update)

**Comment by BlackScorp** [comment] 2024-05-28 13:07
@jensorben thx glad to hear, no this changes will be in V2.6.  the last points are hotfix versions but this will go in 2.6 with some additional changes

**Comment by jensorben** [comment] 2024-05-28 13:09
@BlackScorp Also fine. Can you give us a timeline for release of V 2.6 ?

**Comment by BlackScorp** [comment] 2024-05-29 05:26
@jensorben planned for mid-end of june

**Closed** 2024-06-19 11:47 UTC
